#ifndef COOL_FRONTEND_ERROR_CODES_H
#define COOL_FRONTEND_ERROR_CODES_H

namespace cool {

/// \brief Enumerator of frontend errors
enum class FrontEndErrorCode {
  NO_ERROR = 0,
  LEXER_ERROR_UNTERMINATED_COMMENT = 1,
  LEXER_ERROR_STRING_EXCEEDS_MAX_LENGTH = 2,
  LEXER_ERROR_STRING_CONTAINS_NEWLINE_CHARACTER = 3,
  LEXER_ERROR_STRING_CONTAINS_NULL_CHARACTER = 4,
  LEXER_ERROR_UNTERMINATED_STRING = 5,
  LEXER_ERROR_INVALID_CHARACTER = 6,
  PARSER_ERROR_INVALID_CLASS = 7,
  PARSER_ERROR_INVALID_FEATURE = 8,
  PARSER_ERROR_INVALID_EXPRESSION = 9,
};

} // namespace cool

#endif
